### ISSUE TITLE
electron-forge make error

### ISSUE THREAD

**Issue by stefanJi** [kriasoft/node-sqlite#161]
```
> electron-forge make --platform=darwin --targets=@electron-forge/maker-dmg

An unhandled error has occurred inside Forge:
Compilation errors in the main process: assets by status 3.48 MiB [cached] 5 assets

ERROR in ./node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js 43:20-42
Module not found: Error: Can't resolve 'mock-aws-s3' in '/Users/xxx/Documents/xxx_repo/yy/node_modules/@mapbox/node-pre-gyp/lib/util'
 @ ./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js 15:21-62
 @ ./node_modules/sqlite3/lib/sqlite3-binding.js 1:13-44
 @ ./node_modules/sqlite3/lib/sqlite3.js 2:14-45
 @ ./src/main/tt/sqlitedb.ts 11:0-35 26:28-44
 @ ./src/main/tt/sdkwrapper.ts 17:0-44 43:24-38
 @ ./src/main/ipc/MainIpc.ts 4:0-54 36:19-50 39:19-57 42:19-67 45:19-55 48:19-52
 @ ./src/main/index.ts 8:0-40 22:8-20

ERROR in ./node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js 76:14-32
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/xxx/Documents/xxx_repo/yy/node_modules/@mapbox/node-pre-gyp/lib/util'
 @ ./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js 15:21-62
 @ ./node_modules/sqlite3/lib/sqlite3-binding.js 1:13-44
 @ ./node_modules/sqlite3/lib/sqlite3.js 2:14-45
 @ ./src/main/tt/sqlitedb.ts 11:0-35 26:28-44
 @ ./src/main/tt/sdkwrapper.ts 17:0-44 43:24-38
 @ ./src/main/ipc/MainIpc.ts 4:0-54 36:19-50 39:19-57 42:19-67 45:19-55 48:19-52
 @ ./src/main/index.ts 8:0-40 22:8-20

ERROR in ./node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js 112:15-30
Module not found: Error: Can't resolve 'nock' in '/Users/xxx/Documents/xxx_repo/yy/node_modules/@mapbox/node-pre-gyp/lib/util'
 @ ./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js 15:21-62
 @ ./node_modules/sqlite3/lib/sqlite3-binding.js 1:13-44
 @ ./node_modules/sqlite3/lib/sqlite3.js 2:14-45
 @ ./src/main/tt/sqlitedb.ts 11:0-35 26:28-44
 @ ./src/main/tt/sdkwrapper.ts 17:0-44 43:24-38
 @ ./src/main/ipc/MainIpc.ts 4:0-54 36:19-50 39:19-57 42:19-67 45:19-55 48:19-52
 @ ./src/main/index.ts 8:0-40 22:8-20

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.72.0 compiled with 3 errors and 2 warnings in 14421 ms
Error: Compilation errors in the main process: assets by status 3.48 MiB [cached] 5 assets
orphan modules 1.78 MiB [orphan] 137 modules
runtime modules 1.02 KiB 5 modules
javascript modules 2.71 MiB
  cacheable modules 2.71 MiB 329 modules
  + 19 modules
json modules 409 KiB
  modules by path ./node_modules/@byted-jiyangjy/im-web-sdk/dist/esm/ 383 KiB
    ./node_modules/@byted-jiyangjy/im-web-sdk/dist/esm/emoji/res/images/imsdk_emoji_1.json 3.46 KiB [optional] [built] [code generated]
    ./node_modules/@byted-jiyangjy/im-web-sdk/dist/esm/emoji/res/images/imsdk_emoji_10.json 3.31 KiB [optional] [built] [code generated]
    ./node_modules/@byted-jiyangjy/im-web-sdk/dist/esm/emoji/res/images/imsdk_emoji_100.json 3.13 KiB [optional] [built] [code generated]
    + 111 modules
  modules by path ./node_modules/@mapbox/node-pre-gyp/ 24.2 KiB
    ./node_modules/@mapbox/node-pre-gyp/package.json 1.29 KiB [built] [code generated]
    ./node_modules/@mapbox/node-pre-gyp/lib/util/abi_crosswalk.json 22.9 KiB [built] [code generated]
  ./node_modules/axios/package.json 1.92 KiB [built] [code generated]

WARNING in ./node_modules/ws/lib/buffer-util.js 103:21-42
Module not found: Error: Can't resolve 'bufferutil' in '/Users/xxx/Documents/xxx_repo/yy/node_modules/ws/lib'
 @ ./node_modules/ws/lib/receiver.js 12:42-66
 @ ./node_modules/ws/wrapper.mjs 2:0-41 7:0-79
 @ ./src/main/tt/wsclient.ts 3:0-31 27:16-25 49:63-77
 @ ./src/main/tt/sdkwrapper.ts 18:0-46 51:27-43
 @ ./src/main/ipc/MainIpc.ts 4:0-54 36:19-50 39:19-57 42:19-67 45:19-55 48:19-52
 @ ./src/main/index.ts 8:0-40 22:8-20

WARNING in ./node_modules/ws/lib/validation.js 109:22-47
Module not found: Error: Can't resolve 'utf-8-validate' in '/Users/xxx/Documents/xxx_repo/yy/node_modules/ws/lib'
 @ ./node_modules/ws/lib/receiver.js 13:43-66
 @ ./node_modules/ws/wrapper.mjs 2:0-41 7:0-79
 @ ./src/main/tt/wsclient.ts 3:0-31 27:16-25 49:63-77
 @ ./src/main/tt/sdkwrapper.ts 18:0-46 51:27-43
 @ ./src/main/ipc/MainIpc.ts 4:0-54 36:19-50 39:19-57 42:19-67 45:19-55 48:19-52
 @ ./src/main/index.ts 8:0-40 22:8-20

2 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js 43:20-42
Module not found: Error: Can't resolve 'mock-aws-s3' in '/Users/xxx/Documents/xxx_repo/yy/node_modules/@mapbox/node-pre-gyp/lib/util'
 @ ./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js 15:21-62
 @ ./node_modules/sqlite3/lib/sqlite3-binding.js 1:13-44
 @ ./node_modules/sqlite3/lib/sqlite3.js 2:14-45
 @ ./src/main/tt/sqlitedb.ts 11:0-35 26:28-44
 @ ./src/main/tt/sdkwrapper.ts 17:0-44 43:24-38
 @ ./src/main/ipc/MainIpc.ts 4:0-54 36:19-50 39:19-57 42:19-67 45:19-55 48:19-52
 @ ./src/main/index.ts 8:0-40 22:8-20

ERROR in ./node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js 76:14-32
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/xxx/Documents/xxx_repo/yy/node_modules/@mapbox/node-pre-gyp/lib/util'
 @ ./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js 15:21-62
 @ ./node_modules/sqlite3/lib/sqlite3-binding.js 1:13-44
 @ ./node_modules/sqlite3/lib/sqlite3.js 2:14-45
 @ ./src/main/tt/sqlitedb.ts 11:0-35 26:28-44
 @ ./src/main/tt/sdkwrapper.ts 17:0-44 43:24-38
 @ ./src/main/ipc/MainIpc.ts 4:0-54 36:19-50 39:19-57 42:19-67 45:19-55 48:19-52
 @ ./src/main/index.ts 8:0-40 22:8-20

ERROR in ./node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js 112:15-30
Module not found: Error: Can't resolve 'nock' in '/Users/xxx/Documents/xxx_repo/yy/node_modules/@mapbox/node-pre-gyp/lib/util'
 @ ./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js 15:21-62
 @ ./node_modules/sqlite3/lib/sqlite3-binding.js 1:13-44
 @ ./node_modules/sqlite3/lib/sqlite3.js 2:14-45
 @ ./src/main/tt/sqlitedb.ts 11:0-35 26:28-44
 @ ./src/main/tt/sdkwrapper.ts 17:0-44 43:24-38
 @ ./src/main/ipc/MainIpc.ts 4:0-54 36:19-50 39:19-57 42:19-67 45:19-55 48:19-52
 @ ./src/main/index.ts 8:0-40 22:8-20

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.72.0 compiled with 3 errors and 2 warnings in 14421 ms
    at cb (/Users/xxx/Documents/xxx_repo/yy/node_modules/@electron-forge/plugin-webpack/src/WebpackPlugin.ts:270:31)
    at finalCallback (/Users/xxx/Documents/xxx_repo/yy/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/xxx/Documents/xxx_repo/yy/node_modules/webpack/lib/Compiler.js:458:13
    at Hook.eval [as callAsync] (eval at create (/Users/xxx/Documents/xxx_repo/yy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/xxx/Documents/xxx_repo/yy/node_modules/tapable/lib/Hook.js:18:14)
    at onCompiled (/Users/xxx/Documents/xxx_repo/yy/node_modules/webpack/lib/Compiler.js:456:21)
    at /Users/xxx/Documents/xxx_repo/yy/node_modules/webpack/lib/Compiler.js:1196:17
    at Hook.eval [as callAsync] (eval at create (/Users/xxx/Documents/xxx_repo/yy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/xxx/Documents/xxx_repo/yy/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/xxx/Documents/xxx_repo/yy/node_modules/webpack/lib/Compiler.js:1192:33
    at finalCallback (/Users/xxx/Documents/xxx_repo/yy/node_modules/webpack/lib/Compilation.js:2787:11)
    at /Users/xxx/Documents/xxx_repo/yy/node_modules/webpack/lib/Compilation.js:3092:11
    at Hook.eval [as callAsync] (eval at create (/Users/xxx/Documents/xxx_repo/yy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/xxx/Documents/xxx_repo/yy/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/xxx/Documents/xxx_repo/yy/node_modules/webpack/lib/Compilation.js:3085:38
    at eval (eval at create (/Users/xxx/Documents/xxx_repo/yy/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
```

**Comment by theogravity** [comment]
This looks like an issue with sqlite3 not this project 

https://github.com/TryGhost/node-sqlite3
