### ISSUE TITLE
Exception on INSERT inside loop when trying to retrieve lastID

### ISSUE THREAD

**Issue by heffrey78** [kriasoft/node-sqlite#36]
I’m attempting to use the node-sqlite package. I need to bulk insert rows and get the autoincremented id back. It seems to work when I do one, but in a loop, it fails. Can you help with this or point me in the right direction? Thank you in advance for any help you might have to offer. 

// forecastLocation.js 
const sql = require('./database');

function ForecastLocation() {
}

ForecastLocation.save = async function (forecastLocations) {

  try {
    sql.sqlite.run('begin transaction');

    for (let forecastLocation of forecastLocations) {
      let newDate = new Date();
      newDate = newDate.toISOString();
      let parameters = [forecastLocation.forecastId,
      forecastLocation.lat,
      forecastLocation.lon,
        newDate,
        newDate];

      try {          
          let result = await Promise.resolve(sql.sqlite.run(insertStmt, parameters));
          console.log(result); // contains lastID
      } catch (err) {
        console.log(err);
        throw (err);
      }
    }
  } catch (err) {
    console.log(err);
  } finally {
    sql.sqlite.run('end');
  }
}

// database.js
"use strict"
const path = require('path');
const Promise = require('bluebird');
const sqlite = require('sqlite/legacy');

function Database() {
}

Database.open = function() {
  let filePath = path.join(__dirname, "../../../");
  filePath = path.join(filePath, "resources/db/database-dev.sqlite");
  return sqlite.open(filePath, { Promise });
}

Database.close = function() {
  sqlite.close();
}

module.exports = {Database, sqlite};

// stack trace
Registered protocol succesfully
3277
://eca/
Statement {
  stmt:
   Statement {
     sql: 'INSERT INTO ForecastLocations (forecastId, lat, lon, createdAt, updatedAt) VALUES (?,?,?,?,?)',
     lastID: 1,
     changes: 1 },
  Promise:
   { [Function: Promise]
     TypeError: [Function: TypeError],
     RangeError: [Function: RangeError],
     CancellationError: [Function: SubError],
     TimeoutError: [Function: SubError],
     OperationalError: [Function: OperationalError],
     RejectionError: [Function: OperationalError],
     AggregateError: [Function: SubError],
     _peekContext: [Function],
     onPossiblyUnhandledRejection: [Function],
     onUnhandledRejectionHandled: [Function],
     longStackTraces: [Function],
     hasLongStackTraces: [Function],
     config: [Function],
     getNewLibraryCopy: [Function],
     is: [Function],
     fromCallback: [Function],
     fromNode: [Function],
     all: [Function],
     cast: [Function],
     fulfilled: [Function],
     resolve: [Function],
     rejected: [Function],
     reject: [Function],
     setScheduler: [Function],
     pending: [Function],
     defer: [Function],
     method: [Function],
     try: [Function],
     attempt: [Function],
     bind: [Function],
    PromiseInspection: [Function: PromiseInspection],
     join: [Function],
     Promise: [Circular],
     version: '3.5.0',
     map: [Function],
     using: [Function],
     delay: [Function],
     coroutine: { [Function] addYieldHandler: [Function] },
     spawn: [Function],
     promisify: [Function],
     promisifyAll: [Function],
     props: [Function],
     race: [Function],
     reduce: [Function],
     settle: [Function],
     some: [Function],
     _SomePromiseArray: [Function: SomePromiseArray],
     filter: [Function],
     each: [Function],
     mapSeries: [Function: PromiseMapSeries],
     any: [Function],
     noConflict: [Function: noConflict] } }
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Function._callee2$ (C:/git/onboard/onboard/electron-out/project/ember-electron/main/api/models/forecastLocation.j
s:68:7)
    at tryCatch (C:\git\onboard\onboard\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\git\onboard\onboard\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\git\onboard\onboard\node_modules\regenerator-runtime\runti
me.js:117:21)
    at tryCatch (C:\git\onboard\onboard\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (C:\git\onboard\onboard\node_modules\regenerator-runtime\runtime.js:155:20)
    at C:\git\onboard\onboard\node_modules\regenerator-runtime\runtime.js:165:13
(node:3052) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: forecast.getFore
castLocations is not a function
(node:3052) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.

**Comment by heffrey78** [comment]
I realize that i was killing myself using a foreach type loop instead of a regular for. Solved.
