### ISSUE TITLE
Error:% 1 is not a valid Win32 application

### ISSUE THREAD

**Issue by LazyAndBeyond** [kriasoft/node-sqlite#40]
i keep reciving this after trying to run my discord bot:
C:\Users\AyoubMadrid\Desktop\Mayumi-San>node fix.js
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 nest pas une application Win32 valide.
\\?\C:\Users\AyoubMadrid\Desktop\Mayumi-San\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\AyoubMadrid\Desktop\Mayumi-San\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

C:\Users\AyoubMadrid\Desktop\Mayumi-San>node fix.js
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 nest pas une application Win32 valide.
\\?\C:\Users\AyoubMadrid\Desktop\Mayumi-San\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\AyoubMadrid\Desktop\Mayumi-San\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

**Comment by theogravity** [comment]
This looks like a specific issue with sqlite3 (https://github.com/mapbox/node-sqlite3). I would post there.
